import {CheckCircle2,AlertTriangle,Clock3,ListTodo,Target,Flame,ArrowRight} from "lucide-react";
import {usePlanxStore} from "../store/usePlanxStore";
import {fmtLong,greeting,isoDate} from "../lib/utils";
import {TaskCard} from "../components/TaskCard";
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip} from "recharts";
export function Dashboard({setPage}:{setPage:(x:string)=>void}){
 const tasks=usePlanxStore(s=>s.tasks).filter(t=>!t.archived),today=isoDate(),todayTasks=tasks.filter(t=>t.dueDate===today),completed=todayTasks.filter(t=>t.completed).length,overdue=tasks.filter(t=>!t.completed&&t.dueDate&&t.dueDate<today).length,upcoming=tasks.filter(t=>!t.completed&&t.dueDate&&t.dueDate>today).length,pct=todayTasks.length?Math.round(completed/todayTasks.length*100):0;
 const week=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((name,i)=>({name,value:tasks.filter(t=>t.completedAt&&new Date(t.completedAt).getDay()===(i+1)%7).length}));
 const urgent=tasks.filter(t=>!t.completed&&(t.priority==="urgent"||t.priority==="high")).slice(0,5);
 return <div className="page"><header className="page-header"><div><div className="eyebrow">{fmtLong()}</div><h1>{greeting()}, Sivaram <span>👋</span></h1><p>Let's get things done.</p></div><button className="primary" onClick={()=>dispatchEvent(new CustomEvent("planx:add-task"))}>+ Add Task</button></header>
 <section className="stat-grid"><div className="stat-card featured"><div className="stat-icon"><CheckCircle2/></div><span>Today's progress</span><strong>{completed} / {todayTasks.length}</strong><div className="progress large"><i style={{width:`${pct}%`}}/></div><small>{pct}% complete</small></div><div className="stat-card"><div className="stat-icon"><ListTodo/></div><span>Remaining</span><strong>{Math.max(todayTasks.length-completed,0)}</strong><small>tasks today</small></div><div className="stat-card"><div className="stat-icon"><AlertTriangle/></div><span>Overdue</span><strong>{overdue}</strong><small>need attention</small></div><div className="stat-card"><div className="stat-icon"><Clock3/></div><span>Upcoming</span><strong>{upcoming}</strong><small>scheduled ahead</small></div></section>
 <div className="dashboard-grid"><section><div className="section-head"><div><h2>Today's tasks</h2><p>Your plan for today.</p></div><button className="text-btn" onClick={()=>setPage("Today")}>View today <ArrowRight size={15}/></button></div><div className="task-list">{todayTasks.length?todayTasks.map(t=><TaskCard key={t.id} task={t}/>):<div className="empty"><h3>Your schedule is clear.</h3><p>Enjoy the free time or add something important.</p><button className="primary" onClick={()=>dispatchEvent(new CustomEvent("planx:add-task"))}>Create task</button></div>}</div></section>
 <aside><div className="side-card"><div className="section-head"><div><h2>Next up</h2><p>Priority work.</p></div></div>{urgent.length?urgent.map(t=><div className="compact-task" key={t.id}><span className={`dot ${t.priority}`}/><div><strong>{t.title}</strong><small>{t.dueDate||"No date"}</small></div></div>):<div className="small-empty">No urgent work. Nice.</div>}</div>
 <div className="side-card"><div className="section-head"><div><h2>Weekly activity</h2><p>Completed tasks</p></div></div><ResponsiveContainer width="100%" height={150}><BarChart data={week}><XAxis dataKey="name" fontSize={10}/><YAxis hide/><Tooltip/><Bar dataKey="value" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></aside></div>
 </div>
}
