import {useRef} from "react";
import {usePlanxStore} from "../store/usePlanxStore";
import {useAuthStore} from "../store/useAuthStore";
import type {AppData,Theme} from "../types";
export function Settings(){const user=useAuthStore(s=>s.user),logout=useAuthStore(s=>s.logout);const store=usePlanxStore(),file=useRef<HTMLInputElement>(null);const data:AppData={tasks:store.tasks,projects:store.projects,goals:store.goals,habits:store.habits,notes:store.notes,categories:store.categories,theme:store.theme,onboardingComplete:true,settings:store.settings};
 const exp=(kind:"json"|"csv")=>{let text,type,name;if(kind==="json"){text=JSON.stringify(data,null,2);type="application/json";name="planx-backup.json"}else{text=["id,title,completed,priority,dueDate,categoryId,projectId","..."].join("\n")+"\n"+store.tasks.map(t=>[t.id,t.title.replaceAll(","," "),t.completed,t.priority,t.dueDate??"",t.categoryId,t.projectId??""].join(",")).join("\n");type="text/csv";name="planx-tasks.csv"}const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click()};
 const imp=(f:File)=>{const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(String(r.result));if(!Array.isArray(d.tasks)||!Array.isArray(d.categories)||!Array.isArray(d.projects))throw new Error();if(confirm("Replace current PLANX data with this backup?"))store.replaceData(d)}catch{alert("Invalid PLANX backup. Nothing was changed.")}};r.readAsText(f)};
 return <div className="page"><header className="page-header"><div><h1>Settings</h1><p>Control appearance, behavior and your local data.</p></div></header><div className="settings-grid">
 <section className="settings-card account-settings"><h2>Signed-in account</h2><p>You are signed in as <strong>{user?.name}</strong> ({user?.email}). Your workspace data is separated by your local account.</p><div className="settings-actions"><button className="secondary" onClick={()=>dispatchEvent(new CustomEvent("planx:open-account"))}>View account</button><button className="danger-btn" onClick={logout}>Sign out</button></div></section>
 <section className="settings-card"><h2>Appearance</h2><p>Theme changes apply immediately and persist across refreshes.</p><div className="theme-options">{(["system","light","dark"] as Theme[]).map(x=><button className={store.theme===x?"selected":""} onClick={()=>store.setTheme(x)} key={x}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div><div className="setting-row"><span>Compact mode</span><input type="checkbox" checked={store.settings.compact} onChange={e=>store.updateSettings({compact:e.target.checked})}/></div><div className="setting-row"><span>Animations</span><input type="checkbox" checked={store.settings.animations} onChange={e=>store.updateSettings({animations:e.target.checked})}/></div></section>
 <section className="settings-card"><h2>Notifications</h2><p>Browser notifications require permission and are disabled by default.</p><div className="setting-row"><span>Task notifications</span><input type="checkbox" checked={store.settings.notifications} onChange={async e=>{if(e.target.checked&&"Notification"in window&&Notification.permission==="default")await Notification.requestPermission();store.updateSettings({notifications:e.target.checked})}}/></div><div className="setting-row"><span>Deadline reminders</span><input type="checkbox" checked={store.settings.deadlineReminders} onChange={e=>store.updateSettings({deadlineReminders:e.target.checked})}/></div></section>
 <section className="settings-card"><h2>Data</h2><p>PLANX is local-first. Your task data stays in this browser until you explicitly export or connect a future backend.</p><div className="settings-actions"><button className="secondary" onClick={()=>exp("json")}>Export JSON</button><button className="secondary" onClick={()=>exp("csv")}>Export CSV</button><button className="secondary" onClick={()=>file.current?.click()}>Import JSON</button><input hidden ref={file} type="file" accept=".json" onChange={e=>e.target.files?.[0]&&imp(e.target.files[0])}/><button className="danger-btn" onClick={()=>confirm("Clear ALL local PLANX data? Make a backup first.")&&store.clearAll()}>Clear local data</button></div></section>
 <section className="settings-card"><h2>Keyboard shortcuts</h2>{[["N","New task"],["/","Search"],["T","Today"],["C","Calendar"],["P","Projects"],["Esc","Close modal / focus mode"],["Ctrl/Cmd K","Command palette"]].map(x=><div className="shortcut" key={x[0]}><kbd>{x[0]}</kbd><span>{x[1]}</span></div>)}</section>
 <section className="settings-card"><h2>Future-ready integrations</h2><p>Authentication, cloud sync, AI assistant, calendar integrations, voice, mobile and collaboration are intentionally separated from the local core.</p><div className="future-list"><span>☁ Cloud sync</span><span>🤖 Ask PLANX</span><span>📅 Google / Microsoft Calendar</span><span>📱 Mobile app</span></div></section>
 </div></div>}
